function generateReport(){

let project = document.getElementById("project").value;
let client = document.getElementById("client").value;
let engineer = document.getElementById("engineer").value;
let details = document.getElementById("details").value;


document.getElementById("result").innerHTML =

`

<h3>The SR Homes</h3>

<h4>Construction Engineering Report</h4>

<hr>

<b>Project:</b> ${project}

<br><br>

<b>Client:</b> ${client}

<br><br>

<b>Engineer:</b> ${engineer}

<br><br>

<b>Calculation Summary:</b>

<p>
${details}
</p>

<hr>

<p>
Generated by The SR Homes Construction Calculator
</p>

`;

}
function downloadPDF(){

let project = document.getElementById("project").value;
let client = document.getElementById("client").value;
let engineer = document.getElementById("engineer").value;
let details = document.getElementById("details").value;


let content = `
THE SR HOMES

Construction Engineering Report

Project:
${project}

Client:
${client}

Engineer:
${engineer}

Calculation Summary:

${details}


Generated by:
The SR Homes
Structural Engineering & Quantity Tools
`;

let blob = new Blob([content], {type:"application/pdf"});

let link = document.createElement("a");

link.href = URL.createObjectURL(blob);

link.download = "The_SR_Homes_Report.pdf";

link.click();

}
