function generateReport(){

let project = document.getElementById("project").value;
let client = document.getElementById("client").value;
let engineer = document.getElementById("engineer").value;
let details = document.getElementById("details").value;


document.getElementById("result").innerHTML =

`

<h3>The SR Homes</h3>

<h4>Construction Engineering Report</h4>

<hr>

<b>Project:</b> ${project}

<br><br>

<b>Client:</b> ${client}

<br><br>

<b>Engineer:</b> ${engineer}

<br><br>

<b>Calculation Summary:</b>

<p>
${details}
</p>

<hr>

<p>
Generated by The SR Homes Construction Calculator
</p>

`;

}
